version: "2"
linters:
  default: standard
  enable:
    - bodyclose
    - gocritic
    - gocyclo
    - misspell
    - revive
    - sqlclosecheck
    - whitespace
  settings:
    gocyclo:
      min-complexity: 15
formatters:
  enable:
    - gofumpt
    - goimports
